# Generated by Django 3.0.9 on 2021-12-08 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
        migrations.AlterField(
            model_name='guildinstance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
        migrations.AlterField(
            model_name='specinstance',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
    ]
