# Generated by Django 3.0.9 on 2021-12-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211208_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.IntegerField(default=0),
        ),
    ]
